### ISSUE TITLE
overlay overlap with additionalFieldInfo mod

### ISSUE THREAD

**Issue by mrPassion78** [BigFood2307/FS22_DynamicFieldPrices#1]
![fsScreen_2022_02_06_11_06_17](https://user-images.githubusercontent.com/40406761/153704717-5790702d-f71f-41e8-a1cf-22b2063a216e.png)
![fsScreen_2022_02_06_11_06_21](https://user-images.githubusercontent.com/40406761/153704718-7ce3409b-e7ac-4df3-9c34-79d5f44fee58.png)

here you can see that the position of youre mod text,  overlaps with the mod from: https://github.com/yumi-modding/FS22_additionalFieldInfo.
Would it be possible to shift the text a bit?

I really like youre mod, and adds a bit more variety to the game.. 
Thnx for the mod so far 🥇

**Comment by BigFood2307** [comment]
Hey, thanks for the Comment. I was initially planing to show the diefference right next to the value. Unfortunately this for some reason has issues on mod maps... Thats why I basically copied yumis code to show my stuff. Makes sense that it would overlap. I just pushed a small update, that should move it out of the way when yumis displays are detected.
There is still some weirdness going on on mod maps, but that is the case with either of our mods on its own.
