### ISSUE TITLE
Translation Br

### ISSUE THREAD

**Issue by Myiamoto86** [BigFood2307/FS22_DynamicFieldPrices#10]
Dear friend,

Good Morning.

In a next update, would there be a possibility to include the BR translation?

A translation is attached to the message.

Until.
[locale_br.txt](https://github.com/BigFood2307/FS22_DynamicFieldPrices/files/10306535/locale_br.txt)

**Comment by BigFood2307** [comment]
Hey!

I know this mod has been dead for a while now. Just wasn't interested in FS. 
Thanks for contributing this translation, i just added it on here and will update the mod to modhub after some other fixes soon.
