### ISSUE TITLE
Better contracts compatibility

### ISSUE THREAD

**Issue by Harag9** [BigFood2307/FS22_DynamicFieldPrices#13]
This mod looks like it's a great idea. However I use the better contracts mod that reduces the price of fields based on the number of contracts you do. e.g. I can set it to reduce the price 5% for each contract up to X times, so say 15% off.

I was wondering do you know if your mod is compatible with Better Contracts % discount? It would be great on the expensive greedy fields if I do contracts for the NPC I can get into their "good books" so to speak :)

I have Both mods installed at the moment, and as an example, I see a difference of +8.2 from your mod, and a -10% from the better contracts mod. 

![image](https://github.com/BigFood2307/FS22_DynamicFieldPrices/assets/20284741/768e2b02-b3d0-47c8-b1e1-c0e2efb09d83)

**Comment by BigFood2307** [comment]
Hey!

I have finally come back to some FS. Thanks for this idea. I actually redid my display to use BCs style. I like it more and it seems to work better with some weird mod-map issues.
The actual final price should always have been compatible. Now the display is merged as well. 

The newest version here on gh already is compatible, I will try to get it to modhub asap.
