### ISSUE TITLE
last modhub release 1.0.1.1

### ISSUE THREAD

**Issue by SbSh-DNA-ModDing** [BigFood2307/FS22_DynamicFieldPrices#22]
log entry:
`FS22_DynamicFieldPrices/DynamicFieldPrices.lua:163: table index is nil`

**Comment by BigFood2307** [comment]
Hey, thanks for the report!
There seems to have been a mixup with the released Version.
So the fix that was supposed to work with certain mod maps (I assume you are playing an a modded map?) was not yet in.

Fastest fix is to download the newest release from here, it should have the fix in.
Sorry for that... I will try to get the newer version on modhub faster than planned.

**Comment by SbSh-DNA-ModDing** [comment]
no problem, happens to me sometimes too.
 I found out in the meantime that I have to delete the svg. dynamicFieldPrices.xml before each load so that it works.
 Thanks for the fast fix.
