### ISSUE TITLE
Option to hide percent modifier

### ISSUE THREAD

**Issue by HoveringGoat** [BigFood2307/FS22_DynamicFieldPrices#24]
Please add an option to hide how much the field is discounted or marked up. For role play it would be much more fun to go "hmmm this seems like a really good deal" rather than "oh see its 30% off buy buy buy"

**Comment by HoveringGoat** [comment]
opened a PR adding this functionality.

**Comment by BigFood2307** [comment]
Closed by #25, thanks for the help! #
