### ISSUE TITLE
Zero "Difference"

### ISSUE THREAD

**Issue by tuzlo** [BigFood2307/FS22_DynamicFieldPrices#6]
I am having an issue with a certain map I am playing. The map is Spring Creek ND, a 32x map. The majority of my fields have a difference of 0% and it never changes. Have  done something wrong? Is there a way to make the rest of the fields fluctuate in price?

**Comment by BigFood2307** [comment]
Hi!

Sorry for the very long wait. I have not been playing FS at all. I just loaded up this map and it works as intended. That could be from an update, Im not sure.
For now Im closing this issue unless someone can replicate it
